# Generated by Django 5.2.1 on 2025-05-14 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("e4b70b6e-097e-4b92-9c70-322c76515419"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.TextField()),
                (
                    "user_type",
                    models.CharField(
                        choices=[("AD", "Admin"), ("ED", "Editor"), ("VI", "Viewer")],
                        default="VI",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
